INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (1, '11:10', 214, '10:10', 'Соломчак Т.Я.', 'Орг.анімац.послуг', 1);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (2, '12:30', 203, '11:30', 'Кравченко О.О.', 'Орг.готельного обслугов.', 1);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (3, '13:40', 214, '12:40', 'Соломчак Т.Я.', 'Економіка п-ств', 1);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (6, '13:40', 214, '12:40', 'Соломчак Т.Я.', 'Економіка п-ств', 8);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (5, '12:30', 203, '11:30', 'Кравченко О.О.', 'Орг.готельного обслугов.', 8);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (4, '11:10', 214, '10:10', 'Соломчак Т.Я.', 'Орг.анімац.послуг', 8);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (7, '09:30', 311, '08:30', 'Буца О.В.', 'Маркетинг', 2);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (8, '10:40', 308, '09:40', 'Герговська Н.Я.', 'Культурологія', 2);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (9, '12:00', 311, '11:00', 'Буца О.В.', 'Економічна теорія', 2);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (10, '09:30', 311, '08:30', 'Буца О.В.', 'Маркетинг', 9);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (11, '10:40', 308, '09:40', 'Герговська Н.Я.', 'Культурологія', 9);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (12, '12:00', 311, '11:00', 'Буца О.В.', 'Економічна теорія', 9);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (19, '10:40', 302, '09:40', 'Гостинська О.І.', 'Екологія', 3);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (20, '12:00', 302, '11:00', 'Строгуш І.Я.', 'БЖД', 3);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (21, '13:10', 209, '12:10', 'Долубовська О.Р.', 'Бух.облік', 3);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (22, '10:40', 302, '09:40', 'Гостинська О.І.', 'Екологія', 10);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (23, '12:00', 302, '11:00', 'Строгуш І.Я.', 'БЖД', 10);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (24, '13:10', 209, '12:10', 'Долубовська О.Р.', 'Бух.облік', 10);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (25, '09:30', 311, '08:30', 'Буца О.В.', 'Маркетинг', 4);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (26, '10:40', 214, '09:40', 'Соломчак Т.Я.', 'Орг.анімац.послуг', 4);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (27, '12:00', 209, '11:00', 'Долубовська О.Р.', 'Бух.облік', 4);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (28, '13:10', 214, '12:10', 'Соломчак Т.Я.', 'Економіка п-ств', 4);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (29, '09:30', 311, '08:30', 'Буца О.В.', 'Маркетинг', 11);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (30, '10:40', 214, '09:40', 'Соломчак Т.Я.', 'Орг.анімац.послуг', 11);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (31, '12:00', 311, '11:00', 'Буца О.В.', 'Економічна теорія', 11);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (32, '13:10', 214, '12:10', 'Соломчак Т.Я.', 'Економіка п-ств', 11);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (33, '09:30', 203, '08:30', 'Кравченко О.О.', 'Орг.готельного обслугов.', 5);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (34, '10:40', 214, '09:40', 'Вишатицька О.Я.', 'Організація бізнесу', 5);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (35, '09:30', 203, '08:30', 'Кравченко О.О.', 'Орг.готельного обслугов.', 12);
INSERT INTO public.lessons (id, end_lesson, office, start_lesson, teacher, title, schedule_day_id) VALUES (36, '10:40', 214, '09:40', 'Вишатицька О.Я.', 'Організація бізнесу', 12);
